requires 'perl', '5.008001';

requires 'Path::Tiny';
requires 'JSON::XS';

on 'test' => sub {
  requires 'Test2::V0';
  requires 'Test2::Plugin::SourceDiag';
  requires 'Unicode::GCString';
};

on 'develop' => sub {
  requires 'DDP';
};
